apiVersion: apps/v1
kind: Deployment
metadata:
  name: ReservationSystem
  labels:
    app: ReservationSystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ReservationSystem
  template:
    metadata:
      labels:
        app: ReservationSystem
    spec:
      containers:
        - name: ReservationSystem
          image: username/ReservationSystem:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5